version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3333:3306"
    volumes:
      - ./party-data:/var/lib/mysql
    networks:
      main:
        aliases:
          - mysql.docker
    environment:
      - MYSQL_ROOT_PASSWORD=toor

  party:
    image: party
    ports:
      - "4545:4848"
      - "8585:8080"
      - "9009:9009"
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      main:
        aliases:
          - party.docker
    volumes:
      - ../:/party
      - ./config:/etc/default/tmf/

networks:
  main:
    external: true
